### ISSUE TITLE
Hello world compilation error

### ISSUE THREAD

**Issue by geoffreyPiraprez** [baimont/hello-world#2]
**Compilation no longer works on Ubuntu 24.04.2 LTS, pls fix that.**

<img width="752" height="90" alt="Image" src="https://github.com/user-attachments/assets/db45d426-d354-4ca2-9185-77e0fa8f013f" />
